import os
import time

senha = input("Qual a senha? ")

if senha != "989":
    print("Acesso não liberado")
    exit()
else:
    print("Acesso liberado")
    time.sleep(3)
    os.system("clear")

print("Entrando...")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando...")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando...")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando")
time.sleep(1)
os.system("clear")
print("Entrando.")
time.sleep(1)
os.system("clear")
print("Entrando..")
time.sleep(1)
os.system("clear")
print("Entrando...")
time.sleep(2)
os.system("clear")
print("Z3Z 0S1M3NU")
os.system("clear")
os.system("git clone https://github.com/Matezin12/srd")
os.system("git clone https://github.com/Matezin12/oshdr")
#colocar o novo repositório aqui
os.system("rm -rf omainst.py")
